package me.freakjoost.Dabois.utils;

import java.util.ArrayList;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCactus;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoor;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockDynamicLiquid;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockReed;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSkull;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;

import com.google.common.collect.Sets;

public class Blocks {

	public static ArrayList<Block> registeredBlocks = new ArrayList<Block>();
	
	
	public static ArrayList<Block> getBlocks(){
		return registeredBlocks;
	}
	
	public static void initBlocks(){
		registeredBlocks.add(Block.getBlockFromName("air"));
		registeredBlocks.add(Block.getBlockFromName("stone"));
		registeredBlocks.add((BlockGrass)Block.getBlockFromName("grass"));
		registeredBlocks.add(Block.getBlockFromName("dirt"));
		registeredBlocks.add(Block.getBlockFromName("cobblestone"));
		registeredBlocks.add(Block.getBlockFromName("planks"));
		registeredBlocks.add(Block.getBlockFromName("sapling"));
		registeredBlocks.add(Block.getBlockFromName("bedrock"));
		registeredBlocks.add(Block.getBlockFromName("flowing_water"));
		registeredBlocks.add(Block.getBlockFromName("water"));
		registeredBlocks.add(Block.getBlockFromName("flowing_lava"));
		registeredBlocks.add(Block.getBlockFromName("lava"));
		registeredBlocks.add(Block.getBlockFromName("sand"));
		registeredBlocks.add(Block.getBlockFromName("gravel"));
		registeredBlocks.add(Block.getBlockFromName("gold_ore"));
		registeredBlocks.add(Block.getBlockFromName("iron_ore"));
		registeredBlocks.add(Block.getBlockFromName("coal_ore"));
		registeredBlocks.add(Block.getBlockFromName("log"));
		registeredBlocks.add(Block.getBlockFromName("log2"));
		registeredBlocks.add(Block.getBlockFromName("leaves"));
		registeredBlocks.add(Block.getBlockFromName("leaves2"));
		registeredBlocks.add(Block.getBlockFromName("sponge"));
		registeredBlocks.add(Block.getBlockFromName("glass"));
		registeredBlocks.add(Block.getBlockFromName("lapis_ore"));
		registeredBlocks.add(Block.getBlockFromName("lapis_block"));
		registeredBlocks.add(Block.getBlockFromName("dispenser"));
		registeredBlocks.add(Block.getBlockFromName("sandstone"));
		registeredBlocks.add(Block.getBlockFromName("noteblock"));
		registeredBlocks.add(Block.getBlockFromName("golden_rail"));
		registeredBlocks.add(Block.getBlockFromName("detector_rail"));
		registeredBlocks.add(Block.getBlockFromName("sticky_piston"));
		registeredBlocks.add(Block.getBlockFromName("web"));
		registeredBlocks.add(Block.getBlockFromName("tallgrass"));
		registeredBlocks.add(Block.getBlockFromName("deadbush"));
		registeredBlocks.add(Block.getBlockFromName("piston"));
		registeredBlocks.add(Block.getBlockFromName("piston_head"));
		registeredBlocks.add(Block.getBlockFromName("wool"));
		registeredBlocks.add(Block.getBlockFromName("piston_extension"));
		registeredBlocks.add(Block.getBlockFromName("yellow_flower"));
		registeredBlocks.add(Block.getBlockFromName("red_flower"));
		registeredBlocks.add(Block.getBlockFromName("brown_mushroom"));
		registeredBlocks.add(Block.getBlockFromName("red_mushroom"));
		registeredBlocks.add(Block.getBlockFromName("gold_block"));
		registeredBlocks.add(Block.getBlockFromName("iron_block"));
		registeredBlocks.add(Block.getBlockFromName("double_stone_slab"));
		registeredBlocks.add(Block.getBlockFromName("stone_slab"));
		registeredBlocks.add(Block.getBlockFromName("brick_block"));
		registeredBlocks.add(Block.getBlockFromName("bookshelf"));
		registeredBlocks.add(Block.getBlockFromName("mossy_cobblestone"));
		registeredBlocks.add(Block.getBlockFromName("obsidian"));
		registeredBlocks.add(Block.getBlockFromName("torch"));
		registeredBlocks.add(Block.getBlockFromName("fire"));
		registeredBlocks.add(Block.getBlockFromName("mob_spawner"));
		registeredBlocks.add(Block.getBlockFromName("oak_stairs"));
		registeredBlocks.add(Block.getBlockFromName("chest"));
		registeredBlocks.add(Block.getBlockFromName("redstone_wire"));
		registeredBlocks.add(Block.getBlockFromName("diamond_ore"));
		registeredBlocks.add(Block.getBlockFromName("diamond_block"));
		registeredBlocks.add(Block.getBlockFromName("crafting_table"));
		registeredBlocks.add(Block.getBlockFromName("wheat"));
		registeredBlocks.add(Block.getBlockFromName("farmland"));
		registeredBlocks.add(Block.getBlockFromName("furnace"));
		registeredBlocks.add(Block.getBlockFromName("lit_furnace"));
		registeredBlocks.add(Block.getBlockFromName("wooden_door"));
		registeredBlocks.add(Block.getBlockFromName("spruce_door"));
		registeredBlocks.add(Block.getBlockFromName("birch_door"));
		registeredBlocks.add(Block.getBlockFromName("jungle_door"));
		registeredBlocks.add(Block.getBlockFromName("acacia_door"));
		registeredBlocks.add(Block.getBlockFromName("dark_oak_door"));
		registeredBlocks.add(Block.getBlockFromName("ladder"));
		registeredBlocks.add(Block.getBlockFromName("rail"));
		registeredBlocks.add(Block.getBlockFromName("stone_stairs"));
		registeredBlocks.add(Block.getBlockFromName("wall_sign"));
		registeredBlocks.add(Block.getBlockFromName("lever"));
		registeredBlocks.add(Block.getBlockFromName("stone_pressure_plate"));
		registeredBlocks.add(Block.getBlockFromName("iron_door"));
		registeredBlocks.add(Block.getBlockFromName("wooden_pressure_plate"));
		registeredBlocks.add(Block.getBlockFromName("redstone_ore"));
		registeredBlocks.add(Block.getBlockFromName("lit_redstone_ore"));
		registeredBlocks.add(Block.getBlockFromName("unlit_redstone_torch"));
		registeredBlocks.add(Block.getBlockFromName("redstone_torch"));
		registeredBlocks.add(Block.getBlockFromName("stone_button"));
		registeredBlocks.add(Block.getBlockFromName("snow_layer"));
		registeredBlocks.add(Block.getBlockFromName("ice"));
		registeredBlocks.add(Block.getBlockFromName("snow"));
		registeredBlocks.add(Block.getBlockFromName("cactus"));
		registeredBlocks.add(Block.getBlockFromName("clay"));
		registeredBlocks.add(Block.getBlockFromName("reeds"));
		registeredBlocks.add(Block.getBlockFromName("jukebox"));
		registeredBlocks.add(Block.getBlockFromName("fence"));
		registeredBlocks.add(Block.getBlockFromName("spruce_fence"));
		registeredBlocks.add(Block.getBlockFromName("birch_fence"));
		registeredBlocks.add(Block.getBlockFromName("jungle_fence"));
		registeredBlocks.add(Block.getBlockFromName("dark_oak_fence"));
		registeredBlocks.add(Block.getBlockFromName("pumpkin"));
		registeredBlocks.add(Block.getBlockFromName("netherrack"));
		registeredBlocks.add(Block.getBlockFromName("soul_sand"));
		registeredBlocks.add(Block.getBlockFromName("glowstone"));
		registeredBlocks.add(Block.getBlockFromName("portal"));
		registeredBlocks.add(Block.getBlockFromName("lit_pumpkin"));
		registeredBlocks.add(Block.getBlockFromName("cake"));
		registeredBlocks.add(Block.getBlockFromName("unpowered_repeater"));
		registeredBlocks.add(Block.getBlockFromName("acacia_fence"));
		registeredBlocks.add(Block.getBlockFromName("powered_repeater"));
		registeredBlocks.add(Block.getBlockFromName("trapdoor"));
		registeredBlocks.add(Block.getBlockFromName("monster_egg"));
		registeredBlocks.add(Block.getBlockFromName("stonebrick"));
		registeredBlocks.add(Block.getBlockFromName("brown_mushroom_block"));
		registeredBlocks.add(Block.getBlockFromName("red_mushroom_block"));
		registeredBlocks.add(Block.getBlockFromName("iron_bars"));
		registeredBlocks.add(Block.getBlockFromName("glass_pane"));
		registeredBlocks.add(Block.getBlockFromName("melon_block"));
		registeredBlocks.add(Block.getBlockFromName("pumpkin_stem"));
		registeredBlocks.add(Block.getBlockFromName("melon_stem"));
		registeredBlocks.add(Block.getBlockFromName("vine"));
		registeredBlocks.add(Block.getBlockFromName("fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("spruce_fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("birch_fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("jungle_fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("dark_oak_fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("acacia_fence_gate"));
		registeredBlocks.add(Block.getBlockFromName("brick_stairs"));
		registeredBlocks.add(Block.getBlockFromName("stone_brick_stairs"));
		registeredBlocks.add(Block.getBlockFromName("mycelium"));
		registeredBlocks.add(Block.getBlockFromName("waterlily"));
		registeredBlocks.add(Block.getBlockFromName("nether_brick"));
		registeredBlocks.add(Block.getBlockFromName("nether_brick_fence"));
		registeredBlocks.add(Block.getBlockFromName("nether_brick_stairs"));
		registeredBlocks.add(Block.getBlockFromName("nether_wart"));
		registeredBlocks.add(Block.getBlockFromName("enchanting_table"));
		registeredBlocks.add(Block.getBlockFromName("brewing_stand"));
		registeredBlocks.add(Block.getBlockFromName("cauldron"));
		registeredBlocks.add(Block.getBlockFromName("end_portal"));
		registeredBlocks.add(Block.getBlockFromName("end_portal_frame"));
		registeredBlocks.add(Block.getBlockFromName("end_stone"));
		registeredBlocks.add(Block.getBlockFromName("dragon_egg"));
		registeredBlocks.add(Block.getBlockFromName("redstone_lamp"));
		registeredBlocks.add(Block.getBlockFromName("lit_redstone_lamp"));
		registeredBlocks.add(Block.getBlockFromName("double_wooden_slab"));
		registeredBlocks.add(Block.getBlockFromName("wooden_slab"));
		registeredBlocks.add(Block.getBlockFromName("cocoa"));
		registeredBlocks.add(Block.getBlockFromName("sandstone_stairs"));
		registeredBlocks.add(Block.getBlockFromName("emerald_ore"));
		registeredBlocks.add(Block.getBlockFromName("ender_chest"));
		registeredBlocks.add(Block.getBlockFromName("tripwire_hook"));
		registeredBlocks.add(Block.getBlockFromName("tripwire"));
		registeredBlocks.add(Block.getBlockFromName("emerald_block"));
		registeredBlocks.add(Block.getBlockFromName("spruce_stairs"));
		registeredBlocks.add(Block.getBlockFromName("birch_stairs"));
		registeredBlocks.add(Block.getBlockFromName("jungle_stairs"));
		registeredBlocks.add(Block.getBlockFromName("command_block"));
		registeredBlocks.add(Block.getBlockFromName("beacon"));
		registeredBlocks.add(Block.getBlockFromName("cobblestone_wall"));
		registeredBlocks.add(Block.getBlockFromName("flower_pot"));
		registeredBlocks.add(Block.getBlockFromName("carrots"));
		registeredBlocks.add(Block.getBlockFromName("potatoes"));
		registeredBlocks.add(Block.getBlockFromName("wooden_button"));
		registeredBlocks.add(Block.getBlockFromName("skull"));
		registeredBlocks.add(Block.getBlockFromName("anvil"));
		registeredBlocks.add(Block.getBlockFromName("trapped_chest"));
		registeredBlocks.add(Block.getBlockFromName("light_weighted_pressure_plate"));
		registeredBlocks.add(Block.getBlockFromName("heavy_weighted_pressure_plate"));
		registeredBlocks.add(Block.getBlockFromName("unpowered_comparator"));
		registeredBlocks.add(Block.getBlockFromName("powered_comparator"));
		registeredBlocks.add(Block.getBlockFromName("daylight_detector"));
		registeredBlocks.add(Block.getBlockFromName("daylight_detector_inverted"));
		registeredBlocks.add(Block.getBlockFromName("redstone_block"));
		registeredBlocks.add(Block.getBlockFromName("quartz_ore"));
		registeredBlocks.add(Block.getBlockFromName("hopper"));
		registeredBlocks.add(Block.getBlockFromName("quartz_block"));
		registeredBlocks.add(Block.getBlockFromName("activator_rail"));
		registeredBlocks.add(Block.getBlockFromName("dropper"));
		registeredBlocks.add(Block.getBlockFromName("stained_hardened_clay"));
		registeredBlocks.add(Block.getBlockFromName("barrier"));
		registeredBlocks.add(Block.getBlockFromName("iron_trapdoor"));
		registeredBlocks.add(Block.getBlockFromName("hay_block"));
		registeredBlocks.add(Block.getBlockFromName("carpet"));
		registeredBlocks.add(Block.getBlockFromName("hardened_clay"));
		registeredBlocks.add(Block.getBlockFromName("coal_block"));
		registeredBlocks.add(Block.getBlockFromName("packed_ice"));
		registeredBlocks.add(Block.getBlockFromName("acacia_stairs"));
		registeredBlocks.add(Block.getBlockFromName("dark_oak_stairs"));
		registeredBlocks.add(Block.getBlockFromName("slime"));
		registeredBlocks.add(Block.getBlockFromName("double_plant"));
		registeredBlocks.add(Block.getBlockFromName("stained_glass"));
		registeredBlocks.add(Block.getBlockFromName("stained_glass_pane"));
		registeredBlocks.add(Block.getBlockFromName("prismarine"));
		registeredBlocks.add(Block.getBlockFromName("sea_lantern"));
		registeredBlocks.add(Block.getBlockFromName("standing_banner"));
		registeredBlocks.add(Block.getBlockFromName("wall_banner"));
		registeredBlocks.add(Block.getBlockFromName("red_sandstone"));
		registeredBlocks.add(Block.getBlockFromName("red_sandstone_stairs"));
		registeredBlocks.add(Block.getBlockFromName("double_stone_slab2"));
		registeredBlocks.add(Block.getBlockFromName("stone_slab2"));
		registeredBlocks.add(Block.getBlockFromName("end_rod"));
		registeredBlocks.add(Block.getBlockFromName("chorus_plant"));
		registeredBlocks.add(Block.getBlockFromName("chorus_flower"));
		registeredBlocks.add(Block.getBlockFromName("purpur_block"));
		registeredBlocks.add(Block.getBlockFromName("acacia_stairs"));
		registeredBlocks.add(Block.getBlockFromName("purpur_pillar"));
		registeredBlocks.add(Block.getBlockFromName("purpur_stairs"));
		registeredBlocks.add(Block.getBlockFromName("purpur_double_slab"));
		registeredBlocks.add(Block.getBlockFromName("purpur_slab"));
		registeredBlocks.add(Block.getBlockFromName("end_bricks"));
		registeredBlocks.add(Block.getBlockFromName("beetroots"));
		registeredBlocks.add(Block.getBlockFromName("grass_path"));
		registeredBlocks.add(Block.getBlockFromName("end_gateway"));
		registeredBlocks.add(Block.getBlockFromName("repeating_command_block"));
		registeredBlocks.add(Block.getBlockFromName("chain_command_block"));
		registeredBlocks.add(Block.getBlockFromName("frosted_ice"));
		registeredBlocks.add(Block.getBlockFromName("magma"));
		registeredBlocks.add(Block.getBlockFromName("nether_wart_block"));
		registeredBlocks.add(Block.getBlockFromName("red_nether_brick"));
		registeredBlocks.add(Block.getBlockFromName("bone_block"));
		registeredBlocks.add(Block.getBlockFromName("structure_void"));
		registeredBlocks.add(Block.getBlockFromName("observer"));
		registeredBlocks.add(Block.getBlockFromName("white_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("orange_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("magenta_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("light_blue_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("yellow_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("lime_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("pink_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("gray_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("silver_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("cyan_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("purple_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("blue_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("brown_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("green_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("red_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("black_shulker_box"));
		registeredBlocks.add(Block.getBlockFromName("white_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("orange_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("magenta_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("light_blue_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("yellow_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("lime_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("pink_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("gray_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("silver_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("cyan_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("purple_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("blue_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("brown_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("green_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("red_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("black_glazed_terracotta"));
		registeredBlocks.add(Block.getBlockFromName("concrete"));
		registeredBlocks.add(Block.getBlockFromName("concrete_powder"));
		registeredBlocks.add(Block.getBlockFromName("structure_block"));
	}
	
}
